spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    create-schemas: true
    enabled: true
    locations: classpath:/db/data_migration,classpath:/db/ddl_migration

exam:
  portal:
    front-url: ${FRONT_URL}
    image-upload-directory: src/main/resources/images/profile
    image-default: default.png
    jwt-header: Authorization
    jwt-secret: ${JWT_SECRET}
    jwt-expiration: 604800


